SR reconstructions of LR labelmaps
Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit pull request #133
Opened 2022-07-14 14:13 UTC by pdedumast

2022-07-14 14:13 UTC, pep8speaks commented
Hello @pdedumast! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pymialsrtk/interfaces/postprocess.py`](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py):

> [Line 424:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py#L424): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 426:1](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py#L426): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 431:1](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py#L431): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 459:9](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py#L459): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 469:5](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py#L469): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 482:1](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/postprocess.py#L482): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`pymialsrtk/interfaces/preprocess.py`](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py):

> [Line 1888:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L1888): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 1927:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L1927): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1955:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L1955): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 1969:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L1969): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 1987:46](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L1987): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2032:5](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L2032): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 2043:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L2043): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 2048:1](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L2048): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 2076:5](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L2076): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 2079:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L2079): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 2098:1](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/preprocess.py#L2098): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`pymialsrtk/interfaces/reconstruction.py`](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/reconstruction.py):

> [Line 531:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/reconstruction.py#L531): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 534:9](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/interfaces/reconstruction.py#L534): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`pymialsrtk/pipelines/anatomical/srr.py`](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py):

> [Line 208:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L208): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (165 > 79 characters)
> [Line 283:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L283): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 79 characters)
> [Line 308:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L308): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 332:13](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L332): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 334:45](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L334): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 335:45](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L335): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 399:31](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9b3e693279ee6b2826a897994c44325699048512/pymialsrtk/pipelines/anatomical/srr.py#L399): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 401:80](https://github. [...]

2022-08-30 07:06 UTC, t-sanchez commented
When the code is run with the configuration file
```
{
    "04": [
        {
            "sr-id": 2,
            "stacks": [1,4,7],
            "custom_interfaces": {
                "skip_svr": true,
                "do_nlm_denoising":true,
                "do_reconstruct_labels": true
            }
        }
    ]
}
```

it fails with the following error during the SDI computation:
```
Traceback (most recent call last):^M
  File "/opt/conda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 398, in run^M
    runtime = self._run_interface(runtime)^M
  File "/opt/conda/lib/python3.7/site-packages/pymialsrtk/interfaces/reconstruction.py", line 556, in _run_interface^M
    self.inputs.stacks_order)^M
  File "/opt/conda/lib/python3.7/site-packages/pymialsrtk/interfaces/utils.py", line 104, in reorder_by_run_ids^M
    id_and_files_ordered.append([[s, f[1]] for f in orig_order if ('run-' + str(s)) in f[1]][0])^M
IndexError: list index out of range^
```

2022-08-30 07:12 UTC, t-sanchez requested changes

2022-08-30 07:12 UTC, t-sanchez commented on pymialsrtk/workflows/postproc_stage.py
> +        p_do_anat_orientation
Missing `p_do_reconstruct_labels`?

2022-08-30 08:17 UTC, pdedumast commented on pymialsrtk/interfaces/preprocess.py
> +                self.inputs.input_label
Yes, when input_label is not connected, `self.inputs.input_label=None`.

2022-08-30 08:56 UTC, pdedumast commented
@t-sanchez , I fixed the processing with `"do_nlm_denoising":true`. Regarding the `mask_hr_label` module, I think you were not on the very last commit, though it is in the postprocessing stage atm.

2022-08-30 11:17 UTC, t-sanchez requested changes

2022-08-30 11:17 UTC, t-sanchez commented on pymialsrtk/interfaces/reconstruction.py
> +    output_hr = File(desc='Output scattered data interpolation image file')
Maybe a small thing, but why was it renamed?
It seems that we now have a mix of `output_hr` and `input_sdi` below.

2022-08-30 11:17 UTC, t-sanchez commented on pymialsrtk/workflows/recon_stage.py
> +        recon_stage.connect(sdiComputation, "output_hr",
Inconsistent usage of `output_hr` and `input_sdi`. This makes it confusing IMO.

2022-08-30 11:17 UTC, t-sanchez commented on pymialsrtk/workflows/recon_stage.py
> +        recon_stage.connect(sdiComputation, "output_hr",
Same as above: `output_hr` goes into `output_sdi`.

2022-08-30 11:44 UTC, merged