170 preprocessing
Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit pull request #173
Opened 2022-08-26 13:03 UTC by t-sanchez

#170: Implement a preprocessing-only stage, with the option to do registration.

2022-08-26 13:03 UTC, pep8speaks commented
Hello @t-sanchez! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`docker/bidsapp/run.py`](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py):

> [Line 96:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L96): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 97:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 106:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 107:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 117:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 79 characters)
> [Line 118:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 79 characters)
> [Line 123:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L123): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 79 characters)
> [Line 124:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L124): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 79 characters)
> [Line 128:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L128): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 129:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L129): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 133:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L133): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 79 characters)
> [Line 134:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L134): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 79 characters)
> [Line 178:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L178): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 229:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L229): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 230:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L230): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 231:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L231): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 244:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L244): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 245:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L245): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 246:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L246): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 247:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L247): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 250:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L250): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 272:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L272): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 275:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L275): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 303:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L303): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 306:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L306): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 307:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L307): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 308:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L308): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 310:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L310): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 79 characters)
> [Line 313:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L313): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 333:80](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/9ee825a23293117e8cbec835b4cf34bbcb086214/docker/bidsapp/run.py#L333): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)

* In the file [`pymialsrtk/interfaces/postprocess.py`](https://github.com/Medical-Ima [...]

2022-08-29 10:10 UTC, pdedumast requested changes
- We should keep the minimum needed in `AnatomicalPipeline` for both derived class `SRReconPipeline` and `PreprocessingPipeline`. For instance, keep SR TV parameters only in `SRReconPipeline`, or report creation.
- Filenames `anatomical_pipeline.py`, `srr.py` and `preprocessing.py` are not consistent. Should "_pipeline" be a suffix for all pipelines or not...? 
- For now, as all pipelines are anatomical, could we just rename `AnatomicalPipeline` into `AbstractPipeline`? This way it would be explicit that this is an abstract class that shouldn't be instantiated as it is.
- While creating all these new classes, it is propably the good opportunity to harmonize variable names (`p_xxx` for function parameters, `m_xxx` for class members).
- Many Docstring (especially for stages definition) are incomplete.
- If the preprocessing stage is intended to be released, this should be specified in usage documentation (`documentation>usage.rst`).
- `various` stage is not really explicit
- For consistency, I would use "proc" as diminutive of processing instead of "pro.

2022-08-30 12:06 UTC, t-sanchez commented on pymialsrtk/interfaces/postprocess.py
> +        run_type = self.inputs.run_type
To be done with #150

2022-08-30 12:07 UTC, t-sanchez commented on pymialsrtk/pipelines/anatomical/preprocessing.py
> +    do_registration = None
Depends on the definition, this could be discussed.

2022-08-31 13:58 UTC, pdedumast approved these changes

2022-08-31 13:58 UTC, pdedumast commented on pymialsrtk/pipelines/anatomical/preprocessing.py
> +                p_dict_custom_interfaces['prepro_do_registration'] \
Still not fan of "prepro" instead of "preproc", sounds very French and not consistent with other pieces of code.

2022-08-31 14:28 UTC, t-sanchez commented on pymialsrtk/pipelines/anatomical/preprocessing.py
> +                p_dict_custom_interfaces['prepro_do_registration'] \
Good remark, I fixed it now.

2022-09-01 06:48 UTC, merged